hdhomerun_host = "192.168.55.12"
hdhr_transcode = false
ffmpeg_path = "/usr/local/bin/ffmpeg"
transcoding_path = "./tmp"
port = "8888"
hd_start = 700

[ffmpeg]
threads = 2
acodec = "libvo_aacenc"
framerate = "24"
h264_preset = "ultrafast"
hls_time = 2
hls_wrap = 10
options = "-loglevel warning -async 1  -tune zerolatency -flags -global_header -fflags +genpts -map 0:0 -map 0:1"

[channel_logos]
702 = "abc.png"
703 = "cw.png"
706 = "cbs.png"
707 = "discovery.png"
708 = "nbc.png"
712 = "fox.png"
718 = "hallmark.png"
719 = "hallmark-movie.png"
720 = "pac12.png"
721 = "721.png"
722 = "outdoor.png"
723 = "foxsports1.png"
724 = "tennis.png"
725 = "cbssports.png"
726 = "bigten.png"
727 = "espnu.png"
728 = "728.png"
729 = "729.png"
730 = "730.png"
731 = "731.png"
732 = "732.png"
733 = "733.png"
734 = "734.png"
735 = "espn.png"
736 = "espn2.png"
737 = "737.png"
738 = "tlc.png"
739 = "abcfamily.png"
742 = "cartoon.png"
744 = "cnn.png"
745 = "hdln.png"
747 = "weather.png"
749 = "749.png"
750 = "history.png"
753 = "fx.png"
754 = "tnt.png"
755 = "tbs.png"
757 = "spike.png"
758 = "usa.png"
759 = "syfy.png"
760 = "comedycentral.png"
764 = "764.png"
765 = "travel.png"
766 = "766.png"
767 = "767.png"
772 = "772.png"
773 = "773.png"
774 = "774.png"
775 = "775.png"
787 = "universal.png"
788 = "788.png"
789 = "789.png"
793 = "bbca.png"
795 = "795.png"
800 = "800.png"
801 = "801.png"
805 = "805.png"
810 = "810.png"


